$image = /home/sex/Pictures/Wallpapers/wallhaven-k8kzwd.jpg

$background = rgba(15130cff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(323027ff)

$inverse_primary = rgba(685f12ff)

$inverse_surface = rgba(e7e2d5ff)

$on_background = rgba(e7e2d5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(373100ff)

$on_primary_container = rgba(f1e48aff)

$on_primary_fixed = rgba(201c00ff)

$on_primary_fixed_variant = rgba(4f4700ff)

$on_secondary = rgba(343117ff)

$on_secondary_container = rgba(ebe3bdff)

$on_secondary_fixed = rgba(1f1c05ff)

$on_secondary_fixed_variant = rgba(4b472bff)

$on_surface = rgba(e7e2d5ff)

$on_surface_variant = rgba(cbc6b5ff)

$on_tertiary = rgba(103726ff)

$on_tertiary_container = rgba(c2ecd3ff)

$on_tertiary_fixed = rgba(002113ff)

$on_tertiary_fixed_variant = rgba(294e3bff)

$outline = rgba(959181ff)

$outline_variant = rgba(4a473aff)

$primary = rgba(d4c871ff)

$primary_container = rgba(4f4700ff)

$primary_fixed = rgba(f1e48aff)

$primary_fixed_dim = rgba(d4c871ff)

$scrim = rgba(000000ff)

$secondary = rgba(cec7a3ff)

$secondary_container = rgba(4b472bff)

$secondary_fixed = rgba(ebe3bdff)

$secondary_fixed_dim = rgba(cec7a3ff)

$shadow = rgba(000000ff)

$source_color = rgba(e5d225ff)

$surface = rgba(15130cff)

$surface_bright = rgba(3b3930ff)

$surface_container = rgba(212017ff)

$surface_container_high = rgba(2c2a21ff)

$surface_container_highest = rgba(37352cff)

$surface_container_low = rgba(1d1c13ff)

$surface_container_lowest = rgba(0f0e07ff)

$surface_dim = rgba(15130cff)

$surface_tint = rgba(d4c871ff)

$surface_variant = rgba(4a473aff)

$tertiary = rgba(a7d0b7ff)

$tertiary_container = rgba(294e3bff)

$tertiary_fixed = rgba(c2ecd3ff)

$tertiary_fixed_dim = rgba(a7d0b7ff)

