# Gaming specific rules
windowrule = match:initial_class ^($games)$, monitor DP-1
windowrule = match:initial_class ^($games)$, workspace 1
windowrule = match:initial_class ^($games)$, fullscreen on
windowrule = match:class ^($games)$, idle_inhibit always

# Floating rules
windowrule {
    name = file-dialogs
    match:title = ^(Open File|Select a File|Open Folder|Save As|Save a File|Library|File Upload|Rename|Compress|Extract|.*wants to save|.*wants to open)(.*)$
    float = on
    center = on
    size = (monitor_w*.45) (monitor_h*.45)
}

windowrule {
    name = settings
    match:class = ^(org.pulseaudio.pavucontrol|pavucontrol|blueman-manager|nm-connection-editor)$
    float = on
    center = on
    size = (monitor_w*.45) (monitor_h*.45)
}

windowrule {
    name = medias
    match:class = ^(mpv|org.gnome.Loupe)$
    float = on
    center = on 
    size = (monitor_w*.60) (monitor_h*.60)
}

windowrule {
    name = id3taggers
    match:class = ^(puddletag|org.musicbrainz.Picard)$
    float = on
    center = on
    size = (monitor_w*.80) (monitor_h*.80)
}

# Specific application to workspaces rules
windowrule {
    name = communication
    match:initial_class = ^(mumble|info.mumble.Mumble|discord|com.discordapp.Discord|gajim|org.gajim.Gajim)$
    workspace = 5
}

windowrule {
    name = obs
    match:initial_class = ^(obs|com.obsproject.Studio)$
    workspace = 6
    render_unfocused = on
}
