# Gaming specific rules
windowrule = match:initial_class ^($games)$, monitor DP-1
windowrule = match:initial_class ^($games)$, workspace 1
windowrule = match:initial_class ^($games)$, fullscreen on
windowrule = match:class ^($games)$, idle_inhibit always

# Floating rules
windowrule {
    name = file-dialogs
    match:title = ^(Open File|Select a File|Open Folder|Save As|Library|File Upload|.*wants to save|.*wants to open)(.*)$
    float = on
    center = on
    size = (monitor_w*.45) (monitor_h*.45)
}

windowrule {
    name = floating-apps
    match:class = ^(org.pulseaudio.pavucontrol|pavucontrol|blueman-manager|nm-connection-editor|puddletag|org.musicbrainz.Picard|mpv|org.gnome.Loupe)$
    float = on
    size = (monitor_w*.60) (monitor_h*.60)
    center = on
}

# Specific application to workspaces rules
windowrule {
    name = discord
    match:initial_class = ^(discord|com.discordapp.Discord)$
    workspace = 5
}

windowrule {
    name = obs
    match:initial_class = ^(obs|com.obsproject.Studio)$
    workspace = 6
    render_unfocused = on
}
