# Gaming specific rules
windowrule = match:initial_class ^($games)$, workspace 5
windowrule = match:initial_class ^($games)$, monitor DP-1
windowrule = match:initial_class ^($games)$, fullscreen on
windowrule = match:class ^($games)$, idle_inhibit always
windowrule = match:initial_class ^($games)$, stay_focused on

windowrule {
    name = floating
    match:class = ^(org.pulseaudio.pavucontrol|pavucontrol|blueman-manager|puddletag|mpv)$
    float = on
    size = 1200 600
    center = on
}

windowrule {
    name = obs
    match:initial_class = ^(obs|com.obsproject.Studio)$
    workspace = 6
}
